### PR TITLE
UI

### PR DESCRIPTION
**Pull request by KaskMIL**
# In this new Pull Request I'm adding the following features:
- Create the app.rb file which contains the methods that serve the console-app entry points:
   - List of books.
   - List of people.
   - List of rentals.
   - Create a book.
   - Create a person.
   - Create rental.
   - Filter rentals.
- Create a main.rb file that contains that presents the user a list of options to perform, lets the user choose an option, ask for parameters if ever needed and exit the app.

### CODE REVIEW

**Comment by ahmetbozaci** [comment]
# ❌ ❌ ❌ STATUS: INVALID  ❌ ❌ ❌ 


### Hello @KaskMIL  ✋🏼 
#### You have submitted a project, that is not working. Kindly fix the error and submit for review again.
image


#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏


### Cheers and Happy coding! 💻 👏
coding


___

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification._

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

_Invalid Code Review Request **does not count** into the code reviews limit._

___

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by KaskMIL** [comment]
Hi @ahmetbozaci 
Thanks for the review
As you can see in the video I just recorded, the program is working properly
https://www.loom.com/share/469211343ffd49a1ac5de329d5f539c0
I also asked my coding partner if he can try it and it works as well

**Comment by ahmetbozaci** [comment]
> Hi @ahmetbozaci Thanks for the review As you can see in the video I just recorded, the program is working properly https://www.loom.com/share/469211343ffd49a1ac5de329d5f539c0 I also asked my coding partner if he can try it and it works as well

@KaskMIL Can you submit it for review again?

**Comment by KaskMIL** [comment]
Sure!

**Review by DeliceLydia — APPROVED** [review]
# Hi @KaskMIL, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
